### ISSUE TITLE
Can’t boot on Catalina Beta

### ISSUE THREAD

**Issue by PaulDGillis** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#1]
I currently have the exact same speced laptop as you. I’m still trying to debug, but even with the beta boot options the laptop seems to make it to the Apple logo but then the loading bar never goes past zero. I have a previous set of Kexts that work on the Catalina beta, and am dual booting Mojave. I’m currently investigating if it no longer boots because of the Kexts (Some which I updated) or something else.

**Comment by k-sym** [comment]
When you get the Clover screen, press the right cursor key and navigate to the options menu. On the boot parameters, add a " -v" (space, minus, v) to the line. Hit enter, and go to the bottom of the list and return. Then select the OSX installer. This will put you in verbose mode. You should be able to capture the failure point on the screen. This info will help in diagnosing the issue.

**Comment by PaulDGillis** [comment]
The problem is it makes it past verbose mode, without a an error, but it never finishes booting, it is quite odd. I assume it is something weird going on with Whatever green. Seems Whatever green stops working with UHD 630 on 10.15, but removing WhateverGreen Kext allows me to boot for now.

**Comment by stonevil** [comment]
Sorry, have no time to play around with Catalina.

WhateverGreen already updated for Catalina but you need to download sources and build Kext with Xcode. On machine with preinstalled Catalina and latest beta version Xcode

**Comment by PaulDGillis** [comment]
@stonevil that is plenty alright, I opened the issue as mostly a warning for those that wanted to update. And a place to show my progress on debugging the issue for others.

I’ve been using the latest Catalina ready released Kexts for VirtualSMC, Lilu and WhateverGreen. After compiling my own from Xcode last night, I still can’t get it past the Glitched Apple loading screen after verbose finishes.

**Comment by PaulDGillis** [comment]
I updated to the very latest beta clover version and that seemed to fix it.
