### ISSUE TITLE
RBA 2018/2019 specifics

### ISSUE THREAD

**Issue by hrytskivr** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#12]
Hi, great guide, I know this is a guide for 2019 model, but it still could benefit if you mark which steps could be done for both 2018/2019 RBAs, and which are model-specific.

**Comment by bhagirathbhard** [comment]
@stonevil does indicate in the beginning that besides DSDT patching, the guide can be followed for most of them.

**Comment by hrytskivr** [comment]
Hi @bhagirathbhard, thanks for your reply, I've seen that too, but I still think some patching may apply for all models, for example this weird audio issues we're having on all models etc.

**Comment by bhagirathbhard** [comment]
Hmm, true. Even I own a 2018 Advanced Razer Blade and could have used a bit more help. Maybe @stonevil could add a table of changes between patching for 2018/19 models for Audio, Trackpad and display stuff

**Comment by hrytskivr** [comment]
Also with these new additions to `config.plist` about C states and whatnot, would be great if there are at least a comment on why we need that.

**Comment by stonevil** [comment]
Ok. I will add this
