### ISSUE TITLE
Question: does this build support Thunderbolt hot swapping?

### ISSUE THREAD

**Issue by ghost** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#15]
Question is the title. I know this is usually an issue with laptops that Thunderbolt 3 hot swap doesn't work in a Hackintosh. Basically have to turn the laptop off, plug in the TB3, power on the TB3 device, and then turn the laptop on for it to be recognized in macOS. If you try to turn it on and connect it while macOS is loaded, nothing happens.

Just curious.

Regards

**Comment by TheManchineel** [comment]
Probably not. I haven't found a card yet that has Thunderbolt hotswap working properly under macOS.

**Comment by devcatdad** [comment]
Yeah, kind of what I figured.

**Comment by ghost** [comment]
Yeah, that is kind of what I figured.
