### ISSUE TITLE
Dim on battery doesn't work

### ISSUE THREAD

**Issue by hrytskivr** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#16]
After applying one of the patches in this guide, namely the `hot patch DSDT for brightness settings between reboots`, the functionality of macOS feature `slightly dim screen on battery power` seems to be broken.

**Comment by bhagirathbhard** [comment]
what year razer do you have?

**Comment by hrytskivr** [comment]
rba 2018 144hz 1060

**Comment by bhagirathbhard** [comment]
I don’t think it ever worked for me to be honest

**Comment by hrytskivr** [comment]
It worked for me even without any patches, seriously, after I applied this patch that saves the brightness level over reboots, the dim on battery doesn't work :(

**Comment by stonevil** [comment]
Hmm...
Never cared about this. Actually always disabled on real Mac.
I will take a look when will get new Razer.
