### ISSUE TITLE
macOS will not load using the repo EFI

### ISSUE THREAD

**Issue by ghost** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#18]
Probably going to have to patch my own DSDT/SSDT since my system is a little different. Posting just to confirm.

My system:
Early-2019 Razer Blade Advanced 15 (i7-8750H with RTX 2080)
Samsung EVO 970 2TB SSD
Wifi: BCM94352Z (DW1560)
64GB RAM

Those may be the only deviations and what is making the repo's EFI incompatible with mine.

At any, this is where I am at that works meaning I can boot from the SSD's EFI without using the USB.

- /EFI created by Unibeast and copied over to SSD /EFI
- Used KextBeast to install Kexts to /L/E/ from the /Extensions directory of the repo
- Have to modify `config.plist` with the following for the 64GB RAM otherwise get hanging at `RANDOM SEED`. I've done this in both original `config.plis` and the one provided in this repo:
![Screen Shot 2019-04-13 at 6 44 35 pm](https://user-images.githubusercontent.com/51866518/64548588-c372ca80-d2e3-11e9-85f4-748e68a51124.png)

At this point, really only WiFi is working: volume, sound, trackpad, battery indicator, screen brightness, do not work. Without the Kexts installed, WiFi does not work.

Here are the various scenarios I've tried and their out comes. All related to this section of the guide: 

https://github.com/stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#install-efi-and-extensions

- **Following the instructions and just copying over the /EFI**
- **Following the instructions and just copying over the /EFI, but keeping the original `config.plist` that I know works**

I've tried both just copying and "Replacing" when prompted to, and erasing the /EFI first and then copying over... instructions not entirely clear on which to do. This just causes it to hang at the following indefinitely:

![20190908_221757](https://user-images.githubusercontent.com/51866518/64548875-5d3a7780-d2e4-11e9-8b8f-00146ce82f57.jpg)

- **Following the instructions and NOT copying certain files (DSDT, SSDT, and a Kext) if the system is not an exact match**
- **Following the instructions and NOT copying certain files (DSDT, SSDT, and a Kext) if the system is not an exact match, but keeping the original `config.plist` that I know works**
- **Trying just the `config.plist` in the repo by itself**

All of these result in the following which just causes the system to restart (not sure why the image is rotated, but when you click on it, it has the correct orientation):

![20190908_222630](https://user-images.githubusercontent.com/51866518/64548857-54e23c80-d2e4-11e9-8f53-a91a22a13f33.jpg)

Otherwise, there are only two configurations that work:

- **As described above, just the Unibeast /EFI, `config.plist` modified for RAM, and Kexts installed in /L/E**
- **Just the Unibeast /EFI, `config.plist` modified for RAM, Kexts installed in /L/E, and the modified SSDT that are allowed if the system is not an exact match (this provides no discernible additions to functionality however)**

It sounds like I just need to dump and modify DSDT/SSDT to suit my system. The instructions provided should make this a breeze. Just posting really in case there is some other obvious issue that might resolve this.

**Comment by k-sym** [comment]
For the record, I have the exact same system. Early 2019 with the RTX2080 (only 32GB and the Sabrent M.2). I too cannot just 'copy' the EFI and ended up dumping and modifying the SSDT's. It's well worth the time and has certainly paid off. It's now my 'production' machine, my old MBP is now the test machine for Catalina. Apart from the weird power issue after wake, it's a superb machine.

**Comment by ghost** [comment]
Ok, that is what. Thanks for confirming!
