### ISSUE TITLE
After patching DSDT for tracking pad, boot takes almost +3 minutes instead of 30 seconds

### ISSUE THREAD

**Issue by ghost** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#21]
As the title says, anyone else experiencing this? Usually takes about 30 seconds to boot, if that. After I've patched the DSDT for trackpad it takes over three minutes to boot. Same thing after patching for pinning. This is usually what is holding it up:

![20190910_203125](https://user-images.githubusercontent.com/51866518/64666672-f2845b80-d40b-11e9-9da7-cf66fa1625b8.jpg)

Looks like it is related to TPD0. Trackpad still doesn't work after all the waiting. I did get it working once without a significant delay, but I've since had to redo my install, and can't get it back to that, even with the backup of the /EFI I had.

Any suggestions?

**Comment by k-sym** [comment]
Did you verify that your trackpad was indeed 'TPD0' using ioregexplorer before patching?

**Comment by ghost** [comment]
Yeah, I screwed up. I started my `config.plist` over from scratch instead of using the one provided in the repo. Was having backlight and just all kinds of visual artifacts. TonyMac helped identify that there was some issues with the `config.plist` and SSDTs in the repo. So downloaded the UHD630 `config.plist` from RehabMan's repo and started from that. I forgot to enable some of the patches in the ACPI. Once I did that it cleared up the trackpad and boot issues... in addition to backlight and visual artifacts I was having. Only issues I have now is the brightness setting not being saved between boots and the caps lock indicator not working which are issues I can live with.
