### ISSUE TITLE
Trackpad still not working

### ISSUE THREAD

**Issue by Kingsleyrrrr** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#22]

**Comment by Kingsleyrrrr** [comment]
![image](https://user-images.githubusercontent.com/47513252/68683871-81dff380-05a2-11ea-9a42-b65615cd984d.png)

**Comment by mogwai403** [comment]
Hi there, I was able to get the trackpad working by removing the following:
EFI/CLOVER/ACPI/patched/DSDT.aml
EFI/CLOVER/ACPI/patched/SSDT-12-OptTabl.aml
EFI/CLOVER/ACPI/patched/SSDT-USBX.aml
EFI/CLOVER/KEXT/Other/USBMap.kext

Basically patch the above manually

Good luck!
