### ISSUE TITLE
EFI for install?

### ISSUE THREAD

**Issue by wu-hongjun** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#23]
Hi,

I am trying to follow your guide, and when it comes to creating a USB booting device for macOS the USB boot drive I created using Unibeast is not booting into the install screen. Do you have a special EFI for installing? Thanks a lot. I tried the EFI you included in your repo it doesn't work as well. Just FYI I am using the 9750H+2070MQ+240Hz model.

**Comment by soerenkampschroer** [comment]
What SSD are you using? 
Did you flash and configure your bios?

**Comment by wu-hongjun** [comment]
> What SSD are you using?
> Did you flash and configure your bios?

Sabrent 2TB, yes I flashed my BIOS, macOS goes all the way to the progress bar in roughly ten minutes but never go into the installation GUI.

**Comment by stonevil** [comment]
Strange. Have some idea. I will test this weekend.

**Comment by wu-hongjun** [comment]
> Strange. Have some idea. I will test this weekend.

I got it working by first installing Mojave then upgrade to Catalina. There are several things from your repo that doesn't quite work, but it is probably because we have different model (I have 9750H + 2070MQ)

I will post my stuff here https://github.com/Errrneist/Hackintosh-Razer-Blade-Advanced/ later this week.

There are several things:
First, once you got your USB patched, does Bluetooth just start working? I have DW1830 and I can see BT4.1 device in USB bus but does not work. BRCMrepo will cause panic.

Also, can you explain how you drive iGPU? I am struggling on iGPU acceleration.

By the way, I don't know how you managed to inject 1 into audio and still have AppleALC working since I don't think 1 is a valid layout-id for this codec. I injected 3 with all the dsdt and ssdt and then AppleALC starts to work. You can check that from here: https://github.com/acidanthera/applealc/wiki/supported-codecs

Thanks for your reply!

**Comment by boyuanx** [comment]
iGPU for me works out of the box with OpenCore on Catalina 10.15.4 without any device ID or patches aside from WhateverGreen.

**Comment by wu-hongjun** [comment]
> iGPU for me works out of the box with OpenCore on Catalina 10.15.4 without any device ID or patches aside from WhateverGreen.

Which model is yours? To be more specific, which CPU are your computer using?

**Comment by boyuanx** [comment]
> > iGPU for me works out of the box with OpenCore on Catalina 10.15.4 without any device ID or patches aside from WhateverGreen.
> 
> Which model is yours? To be more specific, which CPU are your computer using?

Exactly the same as yours, 9750H

**Comment by wu-hongjun** [comment]
> > > iGPU for me works out of the box with OpenCore on Catalina 10.15.4 without any device ID or patches aside from WhateverGreen.
> > 
> > 
> > Which model is yours? To be more specific, which CPU are your computer using?
> 
> Exactly the same as yours, 9750H

If you are comfortable, can you share your EFI? Thanks!!

**Comment by boyuanx** [comment]
> > > > iGPU for me works out of the box with OpenCore on Catalina 10.15.4 without any device ID or patches aside from WhateverGreen.
> > > 
> > > 
> > > Which model is yours? To be more specific, which CPU are your computer using?
> > 
> > 
> > Exactly the same as yours, 9750H
> 
> If you are comfortable, can you share your EFI? Thanks!!

I'm using OpenCore, so it's probably not very useful since you are following this Clover guide. However, try removing any fake IDs, graphics injections, or framebuffer patches you have and just let WhateverGreen use its default values.

Speaking of which, did you unlock BIOS and set DVMT to 64M?

**Comment by boyuanx** [comment]
I took a look at your GitHub, and FYI getting stuck at `gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0` is due to not disabling Nvidia graphics. Easiest way is by using `-wegnoegpu` with WhateverGreen. No need for SSDT patches.

**Comment by wu-hongjun** [comment]
> I took a look at your GitHub, and FYI getting stuck at `gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0` is due to not disabling Nvidia graphics. Easiest way is by using `-wegnoegpu` with WhateverGreen. No need for SSDT patches.

I tried that as well, no luck. I think it is something wrong with Clover. 
Yes, I did unlocked the BIOS. However, even when I set DVMT to USER it does not show up in the BIOS so I flashed the default value with 64.
I am willing to switch to OpenCore if it works. Did you do any special things with Opencore? Any help is appreciated!

**Comment by boyuanx** [comment]
> > I took a look at your GitHub, and FYI getting stuck at `gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0` is due to not disabling Nvidia graphics. Easiest way is by using `-wegnoegpu` with WhateverGreen. No need for SSDT patches.
> 
> I tried that as well, no luck. I think it is something wrong with Clover.
> Yes, I did unlocked the BIOS. However, even when I set DVMT to USER it does not show up in the BIOS so I flashed the default value with 64.
> I am willing to switch to OpenCore if it works. Did you do any special things with Opencore? Any help is appreciated!

I've attached my EFI. I cleared out certain SMBIOS fields because I have my iMessage and everything working but it's very easy to generate. Literally every single thing is working on my Blade and it really is unbelievable.

Try to follow this guide: https://1revenger1.gitbook.io/laptop-guide/ just to get an idea of what you're doing, but you shouldn't need to fix or modify anything to get macOS to run perfectly (aside from WiFi+BT since I swapped cards).

I have just installed Windows on the same Sabrent 1TB drive and now I have dual boot from a single SSD. Sick!
[EFI_Template.zip](https://github.com/stonevil/Razer_Blade_Advanced_early_2019_Hackintosh/files/4639915/EFI_Template.zip)

It was extremely difficult for me to get this working since nobody has done it with an RBA Mid-2019 model and OpenCore does not support DSDT injection so I had to figure out how to make the same changes with SSDT. All worked out in the end though!

Funnily enough, I was turned away from Clover because the EC0 -> EC patch wasn't sticking no matter what I did...

**Comment by wu-hongjun** [comment]
> > > I took a look at your GitHub, and FYI getting stuck at `gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0` is due to not disabling Nvidia graphics. Easiest way is by using `-wegnoegpu` with WhateverGreen. No need for SSDT patches.
> 
> > 
> 
> > I tried that as well, no luck. I think it is something wrong with Clover.
> 
> > Yes, I did unlocked the BIOS. However, even when I set DVMT to USER it does not show up in the BIOS so I flashed the default value with 64.
> 
> > I am willing to switch to OpenCore if it works. Did you do any special things with Opencore? Any help is appreciated!
> 
> 
> 
> I've attached my EFI. I cleared out certain SMBIOS fields because I have my iMessage and everything working but it's very easy to generate. Literally every single thing is working on my Blade and it really is unbelievable.
> 
> 
> 
> Try to follow this guide: https://1revenger1.gitbook.io/laptop-guide/ just to get an idea of what you're doing, but you shouldn't need to fix or modify anything to get macOS to run perfectly (aside from WiFi+BT since I swapped cards).
> 
> 
> 
> I have just installed Windows on the same Sabrent 1TB drive and now I have dual boot from a single SSD. Sick!
> 
> [EFI_Template.zip](https://github.com/stonevil/Razer_Blade_Advanced_early_2019_Hackintosh/files/4639915/EFI_Template.zip)
> 
> 
> 
> It was extremely difficult for me to get this working since nobody has done it with an RBA Mid-2019 model and OpenCore does not support DSDT injection so I had to figure out how to make the same changes with SSDT. All worked out in the end though!
> 
> 
> 
> Funnily enough, I was turned away from Clover because the EC0 -> EC patch wasn't sticking no matter what I did...
> 
> 

Awesome! iGPU does work out of the box for me. Some things, lik USB and Bluetooth is not working, and I’ll work on those when I get time. I did implemented them in Clover so shouldn’t be too much of a deal. I’ll post on Github once I got them all fixed. Thanks again!

**Comment by boyuanx** [comment]
I made my own USB mapping with Hackintool and for WiFi+BT I swapped to a BCM94360NG which works out of the box as well.

**Comment by wu-hongjun** [comment]
> I made my own USB mapping with Hackintool and for WiFi+BT I swapped to a BCM94360NG which works out of the box as well. 

I just got my USB mapping done. I own a DW1830 and I had to use BRCMPATCHRam3.kext to get it rolling, otherwise wifi works but not Bluetooth.

**Comment by k-sym** [comment]
From the docs:
To be paired with BrcmFirmwareData.kext
BrcmPatchRAM3 for 10.14+ (must be paired with BrcmBluetoothInjector)
BrcmPatchRAM2 for 10.11-10.14
BrcmPatchRAM for 10.10 or older

So BrcmPatchRAM3 needs to be paired with BrcmBluetoothInjector. :)

**Comment by wu-hongjun** [comment]
> From the docs:
> To be paired with BrcmFirmwareData.kext
> BrcmPatchRAM3 for 10.14+ (must be paired with BrcmBluetoothInjector)
> BrcmPatchRAM2 for 10.11-10.14
> BrcmPatchRAM for 10.10 or older
> 
> So BrcmPatchRAM3 needs to be paired with BrcmBluetoothInjector. :)

I have all of them ready, just waiting to be integrated cuz they were working well in the Clover version (I tried adding them in config.plist but got an error guess I am just not familiar enough with OpenCore.) It’s too late now and I have work tomorrow :P

**Comment by Errrneist** [comment]
> > From the docs:
> > To be paired with BrcmFirmwareData.kext
> > BrcmPatchRAM3 for 10.14+ (must be paired with BrcmBluetoothInjector)
> > BrcmPatchRAM2 for 10.11-10.14
> > BrcmPatchRAM for 10.10 or older
> > So BrcmPatchRAM3 needs to be paired with BrcmBluetoothInjector. :)
> 
> I have all of them ready, just waiting to be integrated cuz they were working well in the Clover version (I tried adding them in config.plist but got an error guess I am just not familiar enough with OpenCore.) It’s too late now and I have work tomorrow :P

**Comment by boyuanx** [comment]
@Errrneist let's close up this issue? :)

**Comment by wu-hongjun** [comment]
sure🥳
