### ISSUE TITLE
Bios unlock won't work

### ISSUE THREAD

**Issue by DosPuppet** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#24]
Hi, i'm using a RB advanced mid2019, and after dumping, modifying et flashing the bios, no options in the bios. Can't access new menus in advanced, chipset, etc...
My bios is 1.04 (sep. 2019), and when I dump my flashed bios, all options a passed to USER, but don't work...
Il the new bios locked another way ? Anyone with the same problem ? (I've seen threads about overclocking menus, but for me, it's all of them...)

Thanks anyway for this amazing guide.

**Comment by stonevil** [comment]
Hi, have no idea what is the difference between RBA early and mid 2019. Have no access anymore for RBA so I cannot verify and compare.

Can you share screenshot of the AFUWINGUI app?

**Comment by DosPuppet** [comment]
Thanks, here is the info of AFUWINGUI (modded bios file).

https://ibb.co/h8n1h4Q

**Comment by DosPuppet** [comment]
Hi,
I flashed with the mid 2019 1.02 modded bios in the repo, and it didn't work either. My bios is back to version 1.02, but none of the options is unlocked : no overclocking, vt-d or anythng new... That's strange. Some specific due to some models ? Mine is french, maybe regional stuff ? Any hint is welcome....

**Comment by DosPuppet** [comment]
OK, I unlocked menu access for overclocking (both menu and submenu) and system agent by hex editig and modifying bios file using this guide : http://forum.notebookreview.com/threads/razer-bios-mods-potential-to-unlock-all-hidden-options.830993/

All options are now open, and bios is ready to go.
