### ISSUE TITLE
Unlock Bios

### ISSUE THREAD

**Issue by SharathMahendrasah** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#28]
I tried to unlock bios on my mid 2019 razer blade advanced 15 but am not able to once I swapped my ssd. Using a 2tb Sabrent. Do you have any ideas as to why This drive prevents unlocking of bios?

**Comment by boyuanx** [comment]
I'm having the same issue where certain entries are hidden after swapping to a Sabrent 1TB. I have no idea why but rest assured the settings persist, it's just an UI issue.

**Comment by boyuanx** [comment]
BTW an interesting note: Even booting with no SSD attached gave me the entires. With the Sabrent, most of them stay hidden.

**Comment by SharathMahendrasah** [comment]
Yeah I kinda figured as much once I was able to get everything installed and working. Weird wonder why that is though. Anyway thanks for the reply I’m going to close this thread since it’s not really a problem.

**Comment by 4rtz1z** [comment]
Sorry to open up this again, do you guys found a way so the unlocked menu showed up again ? i'm using RBP17 2019, after i add second ssd drive, yes the problem just like you guys it disappear. 
have you guys tried reinstalling clean bios from razer support and reunlocking ? i wanna try to but my RZ09-0314xx didn't have any bios on Razer Support.
