### ISSUE TITLE
Recommendations/Questions

### ISSUE THREAD

**Issue by PaulDGillis** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#3]
@stonevil First off Thank you for the amazing guide, and the continuing work you've been putting into it.

**Recommendation:** 
1) Adding installation for Linux alongside MacOS, and Windows. I've had a lot of issues getting grub to work with Clover. After Googling, I never found help how to get Grub to be installed and boot able from Clover nor how to get Clover to boot Ubuntu.

2) Using VoodooI2C and VoodooHID to add interrupts to the track pad instead of leaving it in polling mode. (Currently I have my track pad setup with interrupt)

**Question:** Does the Razer Synapse Gaming mode mess with under volting the CPU? https://www.youtube.com/watch?v=rJSeG_Pb3bs This video you linked talks about how going into gaming mode has the power to under volt the GPU but only talks about increasing the CPU Power Limit.

I apologize from my inexperience with Clover/Hackintoshs. I pick up pretty quick on how to do things on my own, but could never figure out how to get all 3 OSes to behave together.

**Comment by stonevil** [comment]
@Pauldg7 

1. ML tasks requires a lot space. Few Tb. Because of the running Linux and ML tasks from external media. Maybe this weekend I will take a look for mixing clover and grub on same drive.

2. Already done just have not time to update documentation. Maybe in next few days.

Depends. My configuration works with no issues with Synapse 3. Basically Synapse doing very small tweaks. So no harm.
No idea how Synapse 3 will play with XTU or Throttlestop or MSI Aftrburner.

**Comment by PaulDGillis** [comment]
@stonevil 
I really appreciate it, I'm sure if I understood more about clover/grub it wouldn't be such a pain to get them to work together. 

If I get time I'll help write/help read over the Voodoo Interrupt docs as I've already set this up as well. Out of curiosity since we have the same model laptop what pin are you using for the interrupt?

I was generally curious how it would work, since I only occasionally use Synapse 3's gaming mode. I usually just leave it on balanced. I'm not sure I'll really play with XTU, Throttlestop, or MSI Afterburner, for the same reasons as you I prefer to do it through the BIOs so it works on all 3 OSes. I'm currently studying Computer Science in University and since classes here can range from all over the place in terms of OS support it is really nice to have one laptop that can run all 3.

**Comment by stonevil** [comment]
> @stonevil
> If I get time I'll help write/help read over the Voodoo Interrupt docs as I've already set this up as well. Out of curiosity since we have the same model laptop what pin are you using for the interrupt?

Please fork repo, update documentation for VoodooI2C and create PR (pull request). Thanks.

**Comment by bhagirathbhard** [comment]
Hey @Pauldg7 could you guide me about this interrupt thing ?

**Comment by samdogg7** [comment]
@stonevil 
Thank you for the amazing guide! 
I own a 2018 Razer Blade Base Model with the following specs:

Graphics Memory | 6 GB
Clockspeed | 1.8 Ghz
Graphic Processor | NVIDIA GeForce GTX 1060
Processor | Intel Core i7-8750H (8th Gen)

Will my device be compatible with your guide? Or should I follow this guide that you referenced?

https://www.tonymacx86.com/threads/guide-razer-blade-15-2018-detailed-install-guide-high-sierra-10-13-6-17g2208-17g5019.264017/

I hope to create this Hackintosh for iOS development. 

A separate question, you mention the NVMe upgrade in your guide using Ubuntu. Is this necessary for OSX to run smoothly? Will it drastically increase performance? I do not see a reference to altering the NVMe in the above-mentioned tonymacx86 guide. 

Thank you and sorry for the simple questions. I am new to the Hackintosh community.

**Comment by PaulDGillis** [comment]
@bhagirathbhard I have an exam I'm preparing for Tuesday (Tomorrow) but after that is finished up I'll fork the repo and add documentation to show how to do it. Polling is fine for using the track pad, having the interrupt is just kinda nice.

@samdogg7 That guide you linked is the guide I'd follow if you're still new to creating a Hackintosh. The Ubuntu part is optional, the guide refers to changing the block size of the NVMe SSD if you have a compatible 4K block SSD (Default SSD in Razer Blade 15 2018/2019 Base/Advanced is Samsung PM981 which is not compatible with 4K blocks). 

Added note on the Samsung PM981, it has to be enabled to work with macOS see https://www.tonymacx86.com/threads/guide-razer-blade-15-2018-detailed-install-guide-high-sierra-10-13-6-17g2208-17g5019.264017/page-65#post-1969367. I however haven't tried this as it was found after I had already upgraded the SSD in my Laptop.

As for the Tonymac guide is for 2018 Advanced and doesn't show you how to enable the track pad. The 2018 Razer Blade 15 Base and Razer Blade 15 2019 have the same track pad so read the DSDT section on this guide when patching the trackpad.

@stonevil I'm going to close this issue to not let it spiral out of control since it has a broad topic, and I don't want answered questions/future questions to get lost down the rabbit hole.

**Comment by samdogg7** [comment]
Thanks @Pauldg7 You made my life much easier :D

**Comment by samdogg7** [comment]
@Pauldg7 I am struggling to understand this post about installing on pm981 ssd: https://www.tonymacx86.com/threads/guide-razer-blade-15-2018-detailed-install-guide-high-sierra-10-13-6-17g2208-17g5019.264017/page-65#post-1969367

Do you understand what he is suggesting to install on the pm981?

**Comment by stonevil** [comment]
> @bhagirathbhard I have an exam I'm preparing for Tuesday (Tomorrow) but after that is finished up I'll fork the repo and add documentation to show how to do it. Polling is fine for using the track pad, having the interrupt is just kinda nice.
> 
> @samdogg7 That guide you linked is the guide I'd follow if you're still new to creating a Hackintosh. The Ubuntu part is optional, the guide refers to changing the block size of the NVMe SSD if you have a compatible 4K block SSD (Default SSD in Razer Blade 15 2018/2019 Base/Advanced is Samsung PM981 which is not compatible with 4K blocks).
> 
> Added note on the Samsung PM981, it has to be enabled to work with macOS see https://www.tonymacx86.com/threads/guide-razer-blade-15-2018-detailed-install-guide-high-sierra-10-13-6-17g2208-17g5019.264017/page-65#post-1969367. I however haven't tried this as it was found after I had already upgraded the SSD in my Laptop.
> 
> As for the Tonymac guide is for 2018 Advanced and doesn't show you how to enable the track pad. The 2018 Razer Blade 15 Base and Razer Blade 15 2019 have the same track pad so read the DSDT section on this guide when patching the trackpad.
> 
> @stonevil I'm going to close this issue to not let it spiral out of control since it has a broad topic, and I don't want answered questions/future questions to get lost down the rabbit hole.

Had chance to update documentation?

**Comment by PaulDGillis** [comment]
@stonevil I've got a bit of time today, I'm going to go ahead and get a fork going and started. What pin did you end up using as well? I'm curious to know if we'll all end up using the same pin (With 3 models of the early 2019 could be different) to put in the DSDT patch or if it'll have to patched manually by everyone.
