### ISSUE TITLE
Cant boot into mac os unless i do boot override

### ISSUE THREAD

**Issue by carlosxfigueroa** [stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#31]
if i select my ssd, it will show the logo and go back into the bios, cant seem to boot off m.2

**Comment by cabasse** [comment]
which blade version do you have? I have a mid 2019 (versus an early 2019 as the author's) and had to remove these kexts:

    EFI/CLOVER/ACPI/patched/DSDT.aml
    EFI/CLOVER/ACPI/patched/SSDT-12-OptTabl.aml
    EFI/CLOVER/ACPI/patched/SSDT-USBX.aml

as well as

CPUFriendDataProvider.kext

before it would boot directly.

**Comment by carlosxfigueroa** [comment]
im on opencore now, and figured this out so ill close the issue in a bit, by chance do you have thunderbolt working or usb c to hdmi?

**Comment by k-sym** [comment]
USB-C to HDMI worked fine on my Blade (I don't have it anymore) after I rebuilt the USB map outlined in the ReadMe.

https://github.com/stonevil/Razer_Blade_Advanced_early_2019_Hackintosh#usb-mapping
